### ISSUE TITLE
Server does not resolve endpoints correctly?

### ISSUE THREAD

**Issue by jayjaybillings** [doecode/server#12]
Taken from our discussion on commit 5fc52b0 originally posted by @IanLee1521 [here](https://github.com/doecode/server/commit/a499ef2db584ddbfab271547cb72ca9d1907700a#commitcomment-22914541):

Right, it runs, but I'm not sure how to test the functionality.

Specifically, browsing the server URLs I don't see the endpoints I would expect. For instance, after it comes up on port 8080, I get a 404 page, with a message of:

```
No context on this server matched or handled this request.
Contexts known to this server are:
/doecode ---> o.e.j.m.p.JettyWebAppContext@7d66e544{/doecode,[file:///vagrant/target/filtered-resources/],AVAILABLE}{[file:///vagrant/target/filtered-resources/]}
```

But then browsing there (localhost:8080/doecode) I get the following directory listing, not the endpoints described in the README:

```
Directory: /doecode/

META-INF/ 	25 bytes 	Jul 4, 2017 9:02:30 PM
WEB-INF/ 	32 bytes 	Jul 4, 2017 9:02:30 PM
css/ 	31 bytes 	Jul 4, 2017 9:02:30 PM
js/ 	65 bytes 	Jul 4, 2017 9:02:30 PM
```

**Comment by jayjaybillings** [comment]
The directory listing is correct. The server does not  publish a splash page or anything, just an API. Ideally going to this address would say that it is only the backend server and point to the API documentation.

I think there are a few questions here for @nensor:
1. Are there unit tests that @IanLee1521 can run?
2. Do you think it would be better for the server to map to /doecode/api instead of /doecode, which is where I think the client would sit?
3. Is there any API documentation available with an example of URLs that he can test? For example, could he navigate to localhost:8080/doecode/records and see a raw list/json stream of the current records?

**Comment by nensor** [comment]
Presently, the unit tests are connector-related.  I plan on putting in some persistence tests, but so far we've been doing those interactively.  As far as the /doecode/api mapping, I'll defer to @twelsch1 on that one, as I  believe it was something with the react-to-java translation or routing.  

The API is currently set up on the /services URL (/doecode/services/metadata, /doecode/services/validation, etc.)  I think we might consider mapping that to / for back-end services, if that doesn't mess up Thomas.  Would it still be okay to have /doecode/metadata, /doecode/validation, etc. here?  

The documentation (first draft) is available via requests to /doecode/services/metadata presently.  I'm working with Thomas to make sure this works properly with the front-end, as some of those mappings mentioned earlier might flummox the CSS/JS files for flatdoc.  In standalone, it seems to come up okay though.  

As far as streams of records, I know Thomas is working on drafting those in alongside the authentication; presently, the metadata the back-end is employing has no concept of ownership.

**Comment by nensor** [comment]
Note that the documentation is published on github, which is where flatdoc sources it from:

https://github.com/doecode/server/src/main/java/gov/osti/services/DOECode API Services.md

I plan to document the other endpoints similarly, so that filename might change.  It's referred to in the WEB-INF/js/docs.jsp base for the documentation.  The flatdoc service takes the basic markdown-format file and themes it for presentation, using a template call Viewable in the jersey GET method in Metadata.java.

**Comment by twelsch1** [comment]
The “server” branch and “client” branch are really “api server” and “front end server”. So, I'm using a proxy to access the "server" branch from the front end. 

The proxy makes it such that, when using the front end url, using /api will give you back the server output. So, if you went to {front_end}/api/metadata/1051 you’d get what the API sends back. The /api will come after whatever the root is in the final version.

I can change the proxy pretty easily if you decide to change how the backend endpoints are set up. We'd also need to change the shiro.ini file but this would be a one line change.

I'm curious, when we publicize this do we want to give folks the address to the main site (e.g using the proxy) or just give them the direct link? I'd lean towards the latter, but there might be reasons for the former.

**Comment by jayjaybillings** [comment]
@twelsch1 I'll have to think about the answer to your question about the address. 

Note that @IanLee1521 is only using the server and is considering writing his own client for LLNL. So in his case he won't be bouncing anything off of api/ but instead going directly to doecode/services, I think.

**Comment by nensor** [comment]
Just a note, but I have added user services and revised the metadata documentation markdown files; they should be available in the src/main/java/gov/osti/services folder.  They are accessible via local installations if you go "bare" to the API endpoint; either doecodeapi/services/user or doecodeapi/services/metadata should get them.

Using Flatdoc to style them presently, but might revise some of the CSS theme that it ships with.  I'll try and keep the API docs up to date as they change.  The User services in particular have had a number of revisions lately.
