### ISSUE TITLE
Instructions for correctly creating database schema?

### ISSUE THREAD

**Issue by jayjaybillings** [doecode/server#13]
Do we need to do anything special to create the database schema? I remember that at an earlier point in the development DOE CODE would attempt to do that on its own.

@SmithRWORNL is trying to setup Postgresql for this at ORNL now and I want to make sure we don't have any problems with the schema.

**Comment by vowelllDOE** [comment]
@SledKnight @nensor please address this today

**Comment by nensor** [comment]
The persistence.xml for eclipselink should be configured such that it will attempt to create or extend tables when the server makes its first JPA call.  That said, I am unsure as to whether or not the schema itself will be created; you may wish to do so, and configure the database user in that setup with permissions to create/alter all tables within that schema.
In my case, I had an existing schema in PostgreSQL, and used a schema-owner database user for development/testing of the application.  In production, I would recommend turning off the "create-or-extend-tables" option, as it impacts performance (once the tables are relatively static).
