### ISSUE TITLE
Requested validation service layer

### ISSUE THREAD

**Issue by nensor** [doecode/server#3]
Added /doecode/services/validation REST endpoints as requested for doecode/client services.  This service will validate DOI entries passed, and if configured, also validate award number values against OSTI's authority of the same.

**Comment by nensor** [comment]
Changed validation endpoint to accept multiple DOI/Award Number values and respond with validity of each as requested.  Presently, although the "validations" may specify more than one rule, it is anticipated that this functionality won't be required (e.g., it will normally receive only a list of DOIs OR a set of award numbers to validate, but  not mix them in a single call.)

Would it be worth exploring to have the service attempt to pattern-match and interpret which validation rule should apply on a value-by-value basis?  @twelsch1 A DOI is easily pattern matched, then checked; if not a DOI, an award number value may be assumed.

**Comment by nensor** [comment]
This is in place in the code, and assuming hooked up from a configuration standpoint, passes initial tests.

Remaining enhancement:  if no configured API pass-through, this service should basically "pass" any input as valid, to prevent breaking the front-end UI in such cases.  @twelsch1 and @jayjaybillings, does this sound reasonable?

**Comment by jayjaybillings** [comment]
In essence yes, but practically I think we would want to make sure that all of our fields are escaped/checked for injection hacks.


Jay Jay Billings
Team Lead, Scientific Software Development
Oak Ridge National Laboratory
Twitter Handle: @jayjaybillings
