### ISSUE TITLE
Add initial support for DOECode output (SOLR?) index

### ISSUE THREAD

**Issue by nensor** [doecode/server#4]
Plan to insert plumbing in the /doecode/services/metadata REST endpoints as applicable to send JSON of the metadata just posted to a configured external SOLR search instance.  If not configured, this step is easily skipped.

**Comment by nensor** [comment]
Added some AWS-specific notes on how I installed SOLR on an EC2 instance to the main repo here.  See SOLR-AWS-NOTES.md in the root.

Might find this informative @jayjaybillings and @twelsch1

**Comment by jayjaybillings** [comment]
That was very informative. Thanks!

**Comment by nensor** [comment]
added notes on deletion and recreation of index if needed, such as sweeping schema changes, etc.

**Comment by nensor** [comment]
Documented processes involved, and SOLR search endpoint API created for basic UI support.

**Comment by nensor** [comment]
Document search services interface on /doecodeapi/services/search, same as the other endpoints, using flatdoc/markdown API documentation.
