### ISSUE TITLE
Autopopulation fails without metadata.xml?

### ISSUE THREAD

**Issue by jayjaybillings** [doecode/server#7]
Autopopulation in repositories without metadata.xml fails with the following error:
```java
doecode/services/metadata/autopopulate
javax.servlet.ServletException: javax.servlet.ServletException: java.lang.NullPointerException
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:138)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:564)
```
We should still be able to pull some metadata if the metadata.yml file is not available.

**Comment by jayjaybillings** [comment]
Unfortunately this broke in the middle of my demo at STIP, but I just skipped it and went to the full example with metadata.yml.

**Comment by nensor** [comment]
What URL was being attempted?  I've done several without metadata.yml successfully.  I did find a NPE in the bitbucket connector however, perhaps that was it?  I tried several invalid github ones and got the expected no-content responses.  I can patch the BB one to make sure it comes up with the same if the API call fails.

There are several test cases in the unit test for the connectors that all work, and I'll put in explicit calls for the current BB problem to ensure it's as expected as well.

**Comment by nensor** [comment]
Added test and fix for NPE in BitBucket.read() method (fails on invalid or incorrectly-entered BB URLs).  Should now log and pass back a no-response return.

**Comment by jayjaybillings** [comment]
I tried https://github.com/doecode/doecode , https://github.com/eclipse/ice , and https://github.com/eclipse/eavp


Jay Jay Billings
Team Lead, Scientific Software Development
Oak Ridge National Laboratory
Twitter Handle: @jayjaybillings
________________________________

**Comment by twelsch1** [comment]
This is working for all of the given addresses on the internal test environment at OSTI. Were you running it locally? My guess would be that the local server wasn't configured with a Github API Key.

**Comment by jayjaybillings** [comment]
That's correct: I wasn't using a GitHub API key. If that is the problem then we should add a discussion about that to the README. I'll give it a try next week to see if it works.


Jay


Jay Jay Billings
Team Lead, Scientific Software Development
Oak Ridge National Laboratory
Twitter Handle: @jayjaybillings
________________________________

**Comment by nensor** [comment]
I intend to put in checks for the various user-defined/profile-driven variables such as api keys to determine whether or not the value was supplied, and deactivate or otherwise handle these situations (e.g., do not attempt to supply github credentials if the key value starts with "$").
