### ISSUE TITLE
GitHub user / apikey?

### ISSUE THREAD

**Issue by IanLee1521** [doecode/server#9]
In the README, it looks like the server needs a github.user and github.apikey, but doesn't describe how those are used...

Specifically, for the API Key, are there particular permissions that it needs?

**Comment by jayjaybillings** [comment]
@nensor should have all the answers you need, but the key is mostly used for pulling down GitHub metadata from the API. So, I think read permissions should be fine.?


Jay Jay Billings
Team Lead, Scientific Software Development
Oak Ridge National Laboratory
Twitter Handle: @jayjaybillings
________________________________

**Comment by nensor** [comment]
Read is fine, correct.  These are presently only used to access GitHub API, and only there to bypass the throttling they do for unauthenticated API requests (60 per hour without a key).

**Comment by nensor** [comment]
If this is answered, I'm closing the issue.  If you need other information or additional clarification, please let me know.
